### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by XuhuiZhou**

### CODE REVIEW

**Comment by XuhuiZhou** [comment]
@ProKil Feel free to add other collaborators to the about us page

**Comment by ProKil** [comment]
Happy to take a look but it seems that I don't have the permission. Would you mind assigning a url to the preview branch, e.g. `sotopia-preview.vercel.app`?

**Comment by ProKil** [comment]
Screenshot 2024-03-12 at 5 05 37 PM

**Comment by XuhuiZhou** [comment]
Try this link:
https://sotopia-website-93ljlqh10-xuhuizhou.vercel.app/ 

image

**Comment by ProKil** [comment]
No it doesn't work. Please assign a url as I showed above. 
Screenshot 2024-03-12 at 9 04 58 PM

**Comment by ProKil** [comment]
i am ok to merge it deploys without errors

**Pull request merged**
